# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a23ecc811a6c4e55e2e681b274ad5fede62cebc83bb36acbe691de66e7668052cf0b4c0c5bc534a828e03fa2a66aa13522bbf8053af059afc7c565782e62ad8

test:
  secret_key_base: 04719f334c9d5857cf3b68ae08aaea82cd5d8d2753553b32de64a5dddbd7e0c8651bbda145a4c4f4a50df74ade420c866fe9c328ef28efc551ce19580e36d3d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
